
server:
  port: 8002


eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/


hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 720000

ribbon:
  ReadTimeout: 720000
  ConnectTimeout: 720000

spring:
  application:
    name: manage-service

  devtools:
      restart:
        enabled: true
      livereload:
        enabled: false

  mvc:
    favicon:
      enabled: true
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/example?useUnicode=true&characterEncoding=utf8&useSSL=false&rewriteBatchedStatements=true
    name:
    username: root
    password: 19950719dwx
    hikari:
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
      maximumPoolSize: 50

  redis:
    # Redis数据库索引（默认为0）
    database: 0
    host: localhost
    port: 6379
    password:
    #redis客户端
    lettuce:
      pool:
      # 连接池最大连接数（使用负值表示没有限制） 默认 8
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        max-wait: -1
        # 连接池中的最大空闲连接 默认 8
        max-idle: 8
        # 连接池中的最小空闲连接 默认 0
        min-idle: 0

#mybatis
mybatis:
    type-aliases-package: com.example.manage.entity
    mapper-locations: classpath:mapper/*.xml

#通用mapper
mapper:
    mappers:
          - com.example.manage.utils.MyMapper
    not-empty: false
    identity: MYSQL

#分页插件
pagehelper:
    helperDialect: mysql
    reasonable: false
    supportMethodsArguments: true
    params: count=countSql
debug: true