
server:
  port: 8002


eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/


hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 720000

ribbon:
  ReadTimeout: 720000
  ConnectTimeout: 720000

spring:
  application:
    name: manage-service

  devtools:
      restart:
        enabled: true
      livereload:
        enabled: false

  mvc:
    favicon:
      enabled: true
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/example?useUnicode=true&characterEncoding=utf8&useSSL=false&rewriteBatchedStatements=true
    name:
    username: root
    password: 1234
    hikari:
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
      maximumPoolSize: 50

    #mybatis
mybatis:
    type-aliases-package: com.example.manage.entity
    mapper-locations: classpath:mapper/*.xml

    #通用mapper
mapper:
    mappers:
          - com.example.manage.utils.MyMapper
    not-empty: false
    identity: MYSQL

    #分页插件
pagehelper:
    helperDialect: mysql
    reasonable: false
    supportMethodsArguments: true
    params: count=countSql
debug: true